=== ztguang/cBPM/src/Criteria/Criteria.Applications/Applications.Fop/exit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by Registred (Registred) -->
<!--W3C Schema generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="Cantiere" type="xs:string"/>
	<xs:element name="Cliente" type="xs:string"/>
	<xs:element name="Consegna" type="xs:string"/>
	<xs:element name="Corsa" type="xs:byte"/>
	<xs:element name="DataPreventivo" type="xs:string"/>
	<xs:element name="DatiGenerali">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DataPreventivo"/>
				<xs:element ref="Venditore"/>
				<xs:element ref="Cliente"/>
				<xs:element ref="Consegna"/>
				<xs:element ref="Pagamento"/>
				<xs:element ref="Cantiere"/>
				<xs:element ref="NoteConsegna"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DatiTecniciGenerali">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="TipoImpianto"/>
				<xs:element ref="NAccessi"/>
				<xs:element ref="NFermate"/>
				<xs:element ref="NServizi"/>
				<xs:element ref="NPersone"/>
				<xs:element ref="Portata"/>
				<xs:element ref="Testata"/>
				<xs:element ref="Vano"/>
				<xs:element ref="Fossa"/>
				<xs:element ref="NImpianto"/>
				<xs:element ref="Disegno"/>
				<xs:element ref="NormaImpianto"/>
				<xs:element ref="Precablato"/>
				<xs:element ref="Legge13"/>
				<xs:element ref="Velocita"/>
				<xs:element ref="Corsa"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DettaglioOrdine">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Meccanica"/>
				<xs:element ref="Elettrica"/>
				<xs:element ref="Idraulica"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Disegno" type="xs:byte"/>
	<xs:element name="Elettrica">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="MainEntity"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MainEntity">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="NoEntity" maxOccurs="unbounded"/>
				<xs:element ref="SubEntity"/>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Fossa" type="xs:byte"/>
	<xs:element name="Idraulica">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="MainEntity"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Legge13" type="xs:byte"/>
	<xs:element name="Meccanica">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="MainEntity"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="NAccessi" type="xs:byte"/>
	<xs:element name="NFermate" type="xs:byte"/>
	<xs:element name="NImpianto" type="xs:byte"/>
	<xs:element name="NPersone" type="xs:byte"/>
	<xs:element name="NServizi" type="xs:byte"/>
	<xs:element name="NoEntity">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="NoEntitySimpleType">
					<xs:attribute name="Name" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="CabinaQuantita"/>
								<xs:enumeration value="CabinaSconto"/>
								<xs:enumeration value="CielinoQuantita"/>
								<xs:enumeration value="CielinoSconto"/>
								<xs:enumeration value="Descrizione"/>
								<xs:enumeration value="Prezzo"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="Order" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="1"/>
								<xs:enumeration value="10"/>
								<xs:enumeration value="2"/>
								<xs:enumeration value="3"/>
								<xs:enumeration value="4"/>
								<xs:enumeration value="7"/>
								<xs:enumeration value="8"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="NoEntitySimpleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="500,5"/>
			<xs:enumeration value="10"/>
			<xs:enumeration value="1"/>
			<xs:enumeration value="3"/>
			<xs:enumeration value="678,5"/>
			<xs:enumeration value="CabinaSimply"/>
			<xs:enumeration value="Cabinacentoducati"/>
			<xs:enumeration value="Value"/>
			<xs:enumeration value="value"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="NormaImpianto" type="xs:byte"/>
	<xs:element name="NoteConsegna" type="xs:string"/>
	<xs:element name="Pagamento" type="xs:string"/>
	<xs:element name="Portata" type="xs:byte"/>
	<xs:element name="Precablato" type="xs:byte"/>
	<xs:element name="Preventivo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DatiGenerali"/>
				<xs:element ref="DatiTecniciGenerali"/>
				<xs:element ref="DettaglioOrdine"/>
			</xs:sequence>
			<xs:attribute name="Idpreventivo" type="xs:byte" use="required"/>
			<xs:attribute name="IdCliente" type="xs:byte" use="required"/>
			<xs:attribute name="IdConsegna" type="xs:byte" use="required"/>
			<xs:attribute name="IdPagamento" type="xs:byte" use="required"/>
			<xs:attribute name="IdCorriere" type="xs:byte" use="required"/>
			<xs:attribute name="IdVenditore" type="xs:byte" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SubEntity">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="NoEntity" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
			<xs:attribute name="Order" type="xs:byte" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Testata" type="xs:byte"/>
	<xs:element name="TipoImpianto" type="xs:boolean"/>
	<xs:element name="Vano" type="xs:byte"/>
	<xs:element name="Velocita" type="xs:byte"/>
	<xs:element name="Venditore" type="xs:string"/>
</xs:schema>

=== ztguang/cBPM/src/Criteria/Criteria.Applications/Applications.Fop/Exit.xml
<Preventivo Idpreventivo="123" IdCliente="123" IdConsegna="123" IdPagamento="123" IdCorriere="123" IdVenditore="123" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\mySoftware\Scenario\src\Applications\Repository\FopApplication\exit.xsd">
	<DatiGenerali>
		<DataPreventivo>14/05/2005</DataPreventivo>
		<Venditore>Paperino</Venditore>
		<Cliente>Pluto</Cliente>
		<Consegna>16/05/2005</Consegna>
		<Pagamento>Contanti</Pagamento>
		<Cantiere>Archimede Inc.</Cantiere>
		<NoteConsegna>Contattare il portiere per la mazzetta</NoteConsegna>
	</DatiGenerali>
	<DatiTecniciGenerali>
		<TipoImpianto>1</TipoImpianto>
		<NAccessi>2</NAccessi>
		<NFermate>3</NFermate>
		<NServizi>4</NServizi>
		<NPersone>5</NPersone>
		<Portata>6</Portata>
		<Testata>7</Testata>
		<Vano>8&amp;</Vano>
		<Fossa>9</Fossa>
		<NImpianto>10</NImpianto>
		<Disegno>11</Disegno>
		<NormaImpianto>12</NormaImpianto>
		<Precablato>13</Precablato>
		<Legge13>14</Legge13>
		<Velocita>13</Velocita>
		<Corsa>14</Corsa>
	</DatiTecniciGenerali>
	<DettaglioOrdine>
		<Meccanica>
			<MainEntity Name="Cabina">
				<NoEntity Name="Descrizione" Order="10">Cabinacentoducati</NoEntity>
				<NoEntity Name="Prezzo" Order="1">500,5</NoEntity>
				<NoEntity Name="CabinaQuantita" Order="8">1</NoEntity>
				<NoEntity Name="CabinaSconto" Order="7">10</NoEntity>
				<SubEntity Name="Celino" Order="6">
					<NoEntity Name="Descrizione" Order="1">CabinaSimply</NoEntity>
					<NoEntity Name="Prezzo" Order="2">678,5</NoEntity>
					<NoEntity Name="CielinoQuantita" Order="3">3</NoEntity>
					<NoEntity Name="CielinoSconto" Order="4">10</NoEntity>
				</SubEntity>
			<MainEntity>
		</Meccanica>
		<Elettrica>
			<MainEntity Name="Cabina">
				<NoEntity Name="Descrizione" Order="10">Cabinacentoducati</NoEntity>
				<NoEntity Name="Prezzo" Order="1">500,5</NoEntity>
				<NoEntity Name="CabinaQuantita" Order="8">500,5</NoEntity>
				<NoEntity Name="CabinaSconto" Order="7">500,5</NoEntity>
				<SubEntity Name="Celino" Order="6">
					<NoEntity Name="Descrizione" Order="1">CabinaSimply</NoEntity>
					<NoEntity Name="Prezzo" Order="2">678,5</NoEntity>
					<NoEntity Name="CielinoQuantita" Order="3">Value</NoEntity>
					<NoEntity Name="CielinoSconto" Order="4">value</NoEntity>
				</SubEntity>
			</MainEntity>
		</Elettrica>
		<Idraulica>
			<MainEntity Name="Cabina">
				<NoEntity Name="Descrizione" Order="10">Cabinacentoducati</NoEntity>
				<NoEntity Name="Prezzo" Order="1">500,5</NoEntity>
				<NoEntity Name="CabinaQuantita" Order="8">500,5</NoEntity>
				<NoEntity Name="CabinaSconto" Order="7">500,5</NoEntity>
				<SubEntity Name="Celino" Order="6">
					<NoEntity Name="Descrizione" Order="1">CabinaSimply</NoEntity>
					<NoEntity Name="Prezzo" Order="2">678,5</NoEntity>
					<NoEntity Name="CielinoQuantita" Order="3">Value</NoEntity>
					<NoEntity Name="CielinoSconto" Order="4">value</NoEntity>
				</SubEntity>
			</MainEntity>
		</Idraulica>
	</DettaglioOrdine>
</Preventivo>
